import type { BenefitType } from "@/types"

export const MOCK_BENEFIT_TYPES: BenefitType[] = [
  { id: "bt-01", name: "Medical Assistance", description: "Financial aid for hospitalization or outpatient medical expenses.", defaultAmount: 5000, maximumAmount: 15000, prorationTiers: [], fyAmounts: [], eligibilityRequirements: "Active member for at least 6 months", requiredMembershipMonths: 6, frequencyLimit: "Twice per year", requiredDocuments: ["Medical Certificate", "Hospital Bill / Receipts", "Valid ID"], approvalRequired: true, status: "Active" },
  { id: "bt-02", name: "Hospital Assistance", description: "Assistance for confinement-related hospital expenses.", defaultAmount: 8000, maximumAmount: 20000, prorationTiers: [], fyAmounts: [], eligibilityRequirements: "Active member, at least 6 months tenure", requiredMembershipMonths: 6, frequencyLimit: "Twice per year", requiredDocuments: ["Hospital Bill", "Discharge Summary", "Valid ID"], approvalRequired: true, status: "Active" },
  { id: "bt-03", name: "Burial Assistance", description: "Assistance to the family of a deceased member.", defaultAmount: 20000, maximumAmount: 20000, prorationTiers: [], fyAmounts: [], eligibilityRequirements: "Member in good standing at time of death", requiredMembershipMonths: 0, frequencyLimit: "Once", requiredDocuments: ["Death Certificate", "Funeral Contract / Receipt", "Beneficiary Valid ID"], approvalRequired: true, status: "Active" },
  { id: "bt-04", name: "Death Benefit", description: "Lump sum benefit released to legal beneficiaries upon death of a member.", defaultAmount: 50000, maximumAmount: 50000, prorationTiers: [], fyAmounts: [], eligibilityRequirements: "Member in good standing at time of death", requiredMembershipMonths: 12, frequencyLimit: "Once", requiredDocuments: ["Death Certificate", "Beneficiary Designation Form", "Beneficiary Valid ID"], approvalRequired: true, status: "Active" },
  { id: "bt-05", name: "Emergency Assistance", description: "Assistance for urgent, unforeseen financial needs.", defaultAmount: 3000, maximumAmount: 10000, prorationTiers: [], fyAmounts: [], eligibilityRequirements: "Active member", requiredMembershipMonths: 3, frequencyLimit: "Once per year", requiredDocuments: ["Incident Report / Affidavit", "Valid ID"], approvalRequired: true, status: "Active" },
  { id: "bt-06", name: "Calamity Assistance", description: "Assistance for members affected by natural or man-made calamities.", defaultAmount: 5000, maximumAmount: 10000, prorationTiers: [], fyAmounts: [], eligibilityRequirements: "Active member residing in affected area", requiredMembershipMonths: 0, frequencyLimit: "Per declared calamity", requiredDocuments: ["Barangay Certification", "Valid ID"], approvalRequired: true, status: "Active" },
  { id: "bt-07", name: "Retirement Benefit", description: "One-time benefit released upon retirement from government service.", defaultAmount: 30000, maximumAmount: 30000, prorationTiers: [], fyAmounts: [], eligibilityRequirements: "Retiring member with at least 10 years of membership", requiredMembershipMonths: 120, frequencyLimit: "Once", requiredDocuments: ["Retirement Order", "Service Record", "Valid ID"], approvalRequired: true, status: "Active" },
  { id: "bt-08", name: "Cash Pabaon", description: "Send-off cash gift for retiring members.", defaultAmount: 10000, maximumAmount: 10000, prorationTiers: [], fyAmounts: [], eligibilityRequirements: "Retiring member in good standing", requiredMembershipMonths: 60, frequencyLimit: "Once", requiredDocuments: ["Retirement Order", "Valid ID"], approvalRequired: true, status: "Active" },
  { id: "bt-09", name: "Solidarity Assistance", description: "Mutual aid benefit funded through the solidarity assistance program.", defaultAmount: 15000, maximumAmount: 15000, prorationTiers: [], fyAmounts: [], eligibilityRequirements: "Active solidarity fund contributor", requiredMembershipMonths: 12, frequencyLimit: "Once", requiredDocuments: ["Solidarity Fund Enrollment Form", "Supporting Documents", "Valid ID"], approvalRequired: true, status: "Active" },
  { id: "bt-10", name: "Other Financial Assistance", description: "Catch-all benefit type for special cases approved by the board.", defaultAmount: 2000, maximumAmount: 10000, prorationTiers: [], fyAmounts: [], eligibilityRequirements: "Subject to board discretion", requiredMembershipMonths: 0, frequencyLimit: "Case-to-case", requiredDocuments: ["Board Resolution / Approval", "Valid ID"], approvalRequired: true, status: "Active" },
]
