import type { LoanType } from "@/types"

export const MOCK_LOAN_TYPES: LoanType[] = [
  {
    id: "lt-01",
    name: "Salary Loan",
    description: "General purpose loan available to all active members in good standing.",
    minAmount: 5000,
    maxAmount: 100000,
    incomeBrackets: [],
    defaultInterestRate: 1.5,
    interestMethod: "Diminishing Balance",
    processingFee: 200,
    maxTermMonths: 24,
    requiredMembershipMonths: 6,
    requiredContributionMonths: 6,
    allowExistingActiveLoan: false,
    status: "Active",
  },
  {
    id: "lt-02",
    name: "Emergency Loan",
    description: "Short-term loan for urgent financial needs.",
    minAmount: 2000,
    maxAmount: 20000,
    incomeBrackets: [],
    defaultInterestRate: 1.0,
    interestMethod: "Flat Interest",
    processingFee: 100,
    maxTermMonths: 12,
    requiredMembershipMonths: 3,
    requiredContributionMonths: 3,
    allowExistingActiveLoan: true,
    status: "Active",
  },
  {
    id: "lt-03",
    name: "Solidarity Assistance Loan",
    description: "Special loan facility supporting solidarity fund members with flexible terms.",
    minAmount: 5000,
    maxAmount: 150000,
    incomeBrackets: [],
    defaultInterestRate: 1.25,
    interestMethod: "Diminishing Balance",
    processingFee: 250,
    maxTermMonths: 36,
    requiredMembershipMonths: 6,
    requiredContributionMonths: 6,
    allowExistingActiveLoan: false,
    status: "Active",
  },
  {
    id: "lt-04",
    name: "Educational Loan",
    description: "Loan for tuition and school-related expenses of members or dependents.",
    minAmount: 5000,
    maxAmount: 50000,
    incomeBrackets: [],
    defaultInterestRate: 1.0,
    interestMethod: "Flat Interest",
    processingFee: 150,
    maxTermMonths: 12,
    requiredMembershipMonths: 6,
    requiredContributionMonths: 6,
    allowExistingActiveLoan: true,
    status: "Active",
  },
  {
    id: "lt-05",
    name: "Multi-Purpose Loan",
    description: "Zero-interest loan for members under special circumstances, subject to board approval.",
    minAmount: 1000,
    maxAmount: 10000,
    incomeBrackets: [],
    defaultInterestRate: 0,
    interestMethod: "Zero Interest",
    processingFee: 0,
    maxTermMonths: 6,
    requiredMembershipMonths: 3,
    requiredContributionMonths: 3,
    allowExistingActiveLoan: true,
    status: "Inactive",
  },
]
