import type { SystemUser, LoginHistoryEntry } from "@/types"

export const MOCK_USERS: SystemUser[] = [
  {
    id: "usr-01",
    fullName: "Maria Corazon D. Santos",
    username: "mcsantos",
    email: "mcsantos@gcgea.gingoog.gov.ph",
    contactNumber: "09171234501",
    roleId: "role-01",
    roleName: "Super Administrator",
    additionalRoleIds: [],
    additionalPermissions: [],
    allowedPermissions: [],
    deniedPermissions: [],
    requirePasswordChange: false,
    status: "Active",
    lastLoginAt: "2026-07-17T08:12:00",
    createdAt: "2024-01-15",
  },
  {
    id: "usr-02",
    fullName: "Ramil B. Ochotorena",
    username: "rochotorena",
    email: "rochotorena@gcgea.gingoog.gov.ph",
    contactNumber: "09171234502",
    roleId: "role-01",
    roleName: "Super Administrator",
    additionalRoleIds: [],
    additionalPermissions: [],
    allowedPermissions: [],
    deniedPermissions: [],
    requirePasswordChange: false,
    status: "Active",
    lastLoginAt: "2026-07-15T14:40:00",
    createdAt: "2024-01-15",
  },
  {
    id: "usr-03",
    fullName: "Ana Liza P. Fernandez",
    username: "alfernandez",
    email: "alfernandez@gcgea.gingoog.gov.ph",
    contactNumber: "09171234503",
    roleId: "role-02",
    roleName: "Membership Officer",
    additionalRoleIds: [],
    additionalPermissions: [],
    allowedPermissions: [],
    deniedPermissions: [],
    requirePasswordChange: false,
    status: "Active",
    lastLoginAt: "2026-07-17T07:55:00",
    createdAt: "2024-02-01",
  },
  {
    id: "usr-04",
    fullName: "Joel A. Ramoso",
    username: "jaramoso",
    email: "jaramoso@gcgea.gingoog.gov.ph",
    contactNumber: "09171234504",
    roleId: "role-02",
    roleName: "Membership Officer",
    additionalRoleIds: [],
    additionalPermissions: [],
    allowedPermissions: [],
    deniedPermissions: [],
    requirePasswordChange: true,
    status: "Active",
    lastLoginAt: "2026-07-16T09:20:00",
    createdAt: "2024-02-01",
  },
  {
    id: "usr-05",
    fullName: "Erwin S. Cabahug",
    username: "escabahug",
    email: "escabahug@gcgea.gingoog.gov.ph",
    contactNumber: "09171234505",
    roleId: "role-03",
    roleName: "Loan Officer",
    additionalRoleIds: [],
    additionalPermissions: [],
    allowedPermissions: [],
    deniedPermissions: [],
    requirePasswordChange: false,
    status: "Active",
    lastLoginAt: "2026-07-17T08:03:00",
    createdAt: "2024-02-10",
  },
  {
    id: "usr-06",
    fullName: "Precious Joy M. Utlang",
    username: "pjutlang",
    email: "pjutlang@gcgea.gingoog.gov.ph",
    contactNumber: "09171234506",
    roleId: "role-03",
    roleName: "Loan Officer",
    // Multiple-roles example: also carries Treasurer duties at her branch office.
    additionalRoleIds: ["role-04"],
    additionalPermissions: [],
    allowedPermissions: [],
    deniedPermissions: [],
    requirePasswordChange: false,
    remarks: "Also handles Treasury functions for the Odiongan satellite office.",
    status: "Active",
    lastLoginAt: "2026-07-14T11:00:00",
    createdAt: "2024-02-10",
  },
  {
    id: "usr-07",
    fullName: "Danilo T. Quiñones",
    username: "dtquinones",
    email: "dtquinones@gcgea.gingoog.gov.ph",
    contactNumber: "09171234507",
    roleId: "role-04",
    roleName: "Treasurer",
    additionalRoleIds: [],
    additionalPermissions: [],
    allowedPermissions: [],
    deniedPermissions: [],
    requirePasswordChange: false,
    status: "Active",
    lastLoginAt: "2026-07-17T07:30:00",
    createdAt: "2024-01-20",
  },
  {
    id: "usr-08",
    fullName: "Girlie B. Nacua",
    username: "gbnacua",
    email: "gbnacua@gcgea.gingoog.gov.ph",
    contactNumber: "09171234508",
    roleId: "role-05",
    roleName: "Benefits Officer",
    additionalRoleIds: [],
    additionalPermissions: [],
    // Directly-allowed-permission example: trusted to override benefit eligibility
    // without needing the full Approving Officer role.
    allowedPermissions: ["benefits.override_eligibility"],
    deniedPermissions: [],
    requirePasswordChange: false,
    remarks: "Granted eligibility override rights per HR memo 2026-014.",
    status: "Active",
    lastLoginAt: "2026-07-16T15:45:00",
    createdAt: "2024-03-05",
  },
  {
    id: "usr-09",
    fullName: "Reynaldo C. Mag-abo",
    username: "rcmagabo",
    email: "rcmagabo@gcgea.gingoog.gov.ph",
    contactNumber: "09171234509",
    roleId: "role-06",
    roleName: "Approving Officer",
    additionalRoleIds: [],
    additionalPermissions: [],
    allowedPermissions: [],
    // Direct-deny-overrides-inherited-role example: still an Approving Officer,
    // but loan approval was revoked pending a conflict-of-interest review.
    deniedPermissions: ["loans.approve"],
    requirePasswordChange: false,
    remarks: "Loan approval access suspended pending COI review — recommend only until cleared.",
    status: "Active",
    lastLoginAt: "2026-07-17T08:20:00",
    createdAt: "2024-01-25",
  },
  {
    id: "usr-10",
    fullName: "Teresita G. Abellanosa",
    username: "tgabellanosa",
    email: "tgabellanosa@gcgea.gingoog.gov.ph",
    contactNumber: "09171234510",
    roleId: "role-07",
    roleName: "Auditor / Viewer",
    additionalRoleIds: [],
    additionalPermissions: [],
    allowedPermissions: [],
    deniedPermissions: [],
    requirePasswordChange: false,
    status: "Active",
    lastLoginAt: "2026-07-10T10:15:00",
    createdAt: "2024-04-18",
  },
  {
    id: "usr-11",
    fullName: "Michael Angelo R. Densing",
    username: "mrdensing",
    email: "mrdensing@gcgea.gingoog.gov.ph",
    contactNumber: "09171234511",
    roleId: "role-03",
    roleName: "Loan Officer",
    additionalRoleIds: [],
    additionalPermissions: [],
    allowedPermissions: [],
    deniedPermissions: [],
    requirePasswordChange: false,
    remarks: "Account deactivated — resigned effective December 2025.",
    status: "Inactive",
    lastLoginAt: "2025-12-02T13:10:00",
    createdAt: "2024-05-02",
  },
  {
    id: "usr-12",
    fullName: "Ferdinand L. Ybañez",
    username: "flybanez",
    email: "flybanez@gcgea.gingoog.gov.ph",
    contactNumber: "09171234512",
    roleId: "role-08",
    roleName: "Senior Loan Officer",
    additionalRoleIds: [],
    additionalPermissions: [],
    allowedPermissions: [],
    deniedPermissions: [],
    requirePasswordChange: false,
    status: "Active",
    lastLoginAt: "2026-07-16T13:05:00",
    createdAt: "2025-03-12",
  },
  {
    id: "usr-13",
    fullName: "Corazon V. Bontuyan",
    username: "cvbontuyan",
    email: "cvbontuyan@gcgea.gingoog.gov.ph",
    contactNumber: "09171234513",
    roleId: "role-09",
    roleName: "Regional Auditor",
    additionalRoleIds: [],
    additionalPermissions: [],
    allowedPermissions: [],
    deniedPermissions: [],
    requirePasswordChange: false,
    status: "Active",
    lastLoginAt: "2026-06-28T09:40:00",
    createdAt: "2025-06-05",
  },
  {
    id: "usr-14",
    fullName: "Jerico S. Amora",
    username: "jsamora",
    email: "jsamora@gcgea.gingoog.gov.ph",
    contactNumber: "09171234514",
    roleId: "role-10",
    roleName: "Branch Coordinator",
    additionalRoleIds: [],
    additionalPermissions: [],
    allowedPermissions: [],
    deniedPermissions: [],
    requirePasswordChange: true,
    status: "Active",
    lastLoginAt: "2026-07-12T10:00:00",
    createdAt: "2025-09-20",
  },
]

export const MOCK_LOGIN_HISTORY: LoginHistoryEntry[] = [
  { id: "lh-01", userId: "usr-01", loginAt: "2026-07-17T08:12:00", ipAddress: "192.168.1.14", device: "Windows 11 · Chrome 126", status: "Success" },
  { id: "lh-02", userId: "usr-01", loginAt: "2026-07-16T08:05:00", ipAddress: "192.168.1.14", device: "Windows 11 · Chrome 126", status: "Success" },
  { id: "lh-03", userId: "usr-01", loginAt: "2026-07-15T14:40:00", ipAddress: "192.168.1.14", device: "Windows 11 · Edge 126", status: "Success" },
  { id: "lh-04", userId: "usr-03", loginAt: "2026-07-17T07:55:00", ipAddress: "192.168.1.22", device: "Windows 10 · Chrome 125", status: "Success" },
  { id: "lh-05", userId: "usr-03", loginAt: "2026-07-14T08:00:00", ipAddress: "192.168.1.22", device: "Windows 10 · Chrome 125", status: "Failed" },
  { id: "lh-06", userId: "usr-09", loginAt: "2026-07-17T08:20:00", ipAddress: "192.168.1.30", device: "Windows 11 · Chrome 126", status: "Success" },
  { id: "lh-07", userId: "usr-11", loginAt: "2025-12-02T13:10:00", ipAddress: "192.168.1.44", device: "Windows 10 · Firefox 118", status: "Success" },
]
