import type { AppearanceSettings, NumberingFormatConfig, ReportCategoryTemplate, ReportExportDesign, SystemSettings } from "@/types"
import { ORGANIZATION } from "@/constants/organization"

function numberingDefault(prefix: string, sequenceLength = 6): NumberingFormatConfig {
  return { prefix, includeYear: prefix !== "GCGEA-MEM", yearFormat: "YYYY", separator: "-", sequenceLength, startingNumber: 1 }
}

function reportCategory(design: Omit<ReportExportDesign, "captionStyle" | "noteStyle">): ReportCategoryTemplate {
  const completeDesign: ReportExportDesign = {
    ...design,
    captionStyle: { fontFamily: "Arial", fontSize: 9, fontWeight: "normal", fontStyle: "italic", textDecoration: "none", textColor: "#475569", textAlignment: "center" },
    noteStyle: { fontFamily: "Arial", fontSize: 9, fontWeight: "normal", fontStyle: "italic", textDecoration: "none", textColor: "#475569", textAlignment: "left" },
  }
  return {
    ...completeDesign,
    captionStyle: { ...completeDesign.captionStyle },
    noteStyle: { ...completeDesign.noteStyle },
    excelTemplate: {
      ...completeDesign,
      captionStyle: { ...completeDesign.captionStyle },
      noteStyle: { ...completeDesign.noteStyle },
    },
  }
}

export const DEFAULT_SYSTEM_SETTINGS: SystemSettings = {
  general: {
    systemName: ORGANIZATION.systemName,
    systemShortName: ORGANIZATION.systemShortName,
    defaultLanguage: "English",
    timeZone: "Asia/Manila",
    dateFormat: "MMMM d, yyyy",
    currency: "PHP",
    fiscalYearStart: "January",
    recordsPerPage: 10,
    membershipRegistrationFee: 100,
    maintenanceMode: false,
    enableAlertTranslations: false,
  },
  organization: {
    organizationName: ORGANIZATION.name,
    acronym: ORGANIZATION.acronym,
    address: ORGANIZATION.address,
    contactNumber: ORGANIZATION.contactNumber,
    email: ORGANIZATION.email,
    website: "www.gingoog.gov.ph",
    authorizedSignatoryName: "Maria Corazon D. Santos",
    authorizedSignatoryPosition: "GCGEA President",
    treasurerName: "Danilo T. Quiñones",
    presidentName: "Maria Corazon D. Santos",
  },
  numbering: {
    member: numberingDefault("GCGEA-MEM"),
    loan: numberingDefault("GCGEA-LN"),
    loanPayment: numberingDefault("GCGEA-PAY"),
    officialReceipt: numberingDefault("GCGEA-OR"),
    contribution: numberingDefault("GCGEA-CON"),
    benefit: numberingDefault("GCGEA-BEN"),
    benefitRelease: numberingDefault("GCGEA-BENREL"),
  },
  loan: {
    // minimumMembershipMonths and reloanPolicy below are placeholders only —
    // the Loan Settings page overwrites them from the real API
    // (loan-settings.service.ts) on load; this local default never reaches
    // the backend's actual enforcement.
    minimumMembershipMonths: 6,
    requirePaidContributions: true,
    minimumPaidContributionMonths: 6,
    requiredMonthlyDuesAmount: 100,
    requireConsecutiveContributionMonths: true,
    applyContributionRuleToReloan: true,
    lockFirstSolidarityLoan: true,
    firstSolidarityLoanAmount: 20000,
    defaultInterestMethod: "Diminishing Balance",
    defaultInterestRate: 1.5,
    defaultProcessingFee: 200,
    defaultPenaltyRate: 2,
    gracePeriodDays: 5,
    maximumActiveLoans: 1,
    allowEligibilityOverride: true,
    requireApproval: true,
    requireReleaseConfirmation: true,
    allowPartialPayment: true,
    allowAdvancePayment: true,
    allowLoanRestructuring: true,
    defaultPaymentMethod: "Payroll Deduction",
    roundingRule: "Nearest Centavo",
    reloanPolicy: {
      reloanEnabled: true,
      reloanAllowAfterFullyPaid: true,
      reloanAllowWhileActive: true,
      reloanMinPaidInstallments: 6,
      reloanMinPaidPercentage: null,
      reloanRequireNoOverdue: true,
      reloanRequireNoPenalty: true,
      reloanDeductPreviousBalance: false,
      reloanMaxConcurrentActiveLoans: 1,
      reloanRequireNewPayslip: true,
      reloanRequireNewAuthorization: true,
      reloanRequireNewPromissoryNote: true,
      reloanRequireFinalApproval: true,
      reloanRequireBoardResolutionAboveLimit: true,
    },
  },
  contribution: {
    defaultMonthlyContribution: 100,
    defaultCashPabaonContribution: 200,
    contributionDueDay: 26,
    enableAutomaticFundAllocation: true,
    requireAllocationValidation: true,
    allowPartialContribution: false,
    allowAdvanceContribution: true,
    duplicateHandling: "Skip duplicates",
    defaultPaymentMethod: "Payroll Deduction",
    contributionReminderEnabled: true,
    requireResolvedVoidedMonths: true,
  },
  benefit: {
    requireApproval: true,
    requireReleaseConfirmation: true,
    allowEligibilityOverride: true,
    defaultApprovalLimit: 20000,
    defaultFrequencyLimit: "Once per year",
    requireSupportingDocuments: true,
    allowMultiplePendingApplications: false,
    requireRetiredStatusForRetirementBenefit: true,
    benefitYearResetMonth: "January",
    nuclearFamilyParentAmount: 15000,
    nuclearFamilyFirstSiblingAmount: 15000,
    nuclearFamilySecondSiblingAmount: 10000,
    nuclearFamilyThirdSiblingAmount: 5000,
    independentSpousalBenefitRights: true,
  },
  notification: {
    inAppNotifications: true,
    emailNotifications: false,
    smsNotifications: false,
    loanApprovalAlerts: true,
    loanDueDateAlerts: true,
    overdueLoanAlerts: true,
    benefitApprovalAlerts: true,
    contributionImportAlerts: true,
    incompleteProfileAlerts: true,
    userAccountAlerts: true,
  },
  security: {
    minimumPasswordLength: 8,
    requireUppercase: true,
    requireLowercase: true,
    requireNumber: true,
    requireSpecialCharacter: false,
    sessionTimeoutMinutes: 30,
    maximumLoginAttempts: 5,
    lockoutDurationMinutes: 15,
    requirePasswordChangeOnFirstLogin: false,
    enableTwoFactorAuth: false,
    auditSensitiveActions: true,
    confirmFinancialTransactions: true,
  },
  backup: {
    automaticBackup: true,
    backupFrequency: "Daily",
    retentionDays: 30,
    includeAttachments: false,
  },
  reportTemplate: {
    countryLine: "Republic of the Philippines",
    organizationLine: "Gingoog City Government Employees Association",
    acronymLine: "(GCGEA)",
    addressLine: "City Hall Compound, Gingoog City",
    leftLogo: "/logo.png",
    rightLogo: "/city-seal-logo.png",
    showGeneratedDate: true,
    checkTemplate: {
      backgroundColor: "#E8F3E8",
      heading: "",
      subheading: "",
      payeeLabel: "Pay to the order of",
      currencyLabel: "Pesos",
      memoPrefix: "Memo:",
      primarySignatoryName: "Joy Fatima C. Baguiz",
      primarySignatoryTitle: "Treasurer",
      secondarySignatoryName: "Casimiro T. Guno",
      secondarySignatoryTitle: "President",
      horizontalMargin: 0.45,
      headerTop: 0.25,
      payeeTop: 1.05,
      wordsTop: 1.65,
      footerBottom: 0.42,
    },
    categoryTemplates: {
      member: reportCategory({ preset: "classic", primaryColor: "#1E3A8A", headerBackground: "#E8EDF3", bodyFontSize: 9, bodyFontFamily: "Arial", bodyFontWeight: "normal", bodyFontStyle: "normal", bodyTextDecoration: "none", bodyTextColor: "#111111", bodyTextAlignment: "left", stripedRows: false, showBorders: true, titleAlignment: "center", orientation: "auto", paperSize: "a4", captionText: "", noteText: "" }),
      contribution: reportCategory({ preset: "modern", primaryColor: "#166534", headerBackground: "#DCFCE7", bodyFontSize: 9, bodyFontFamily: "Arial", bodyFontWeight: "normal", bodyFontStyle: "normal", bodyTextDecoration: "none", bodyTextColor: "#111111", bodyTextAlignment: "left", stripedRows: true, showBorders: true, titleAlignment: "left", orientation: "auto", paperSize: "a4", captionText: "", noteText: "" }),
      loan: reportCategory({ preset: "modern", primaryColor: "#9A3412", headerBackground: "#FFEDD5", bodyFontSize: 9, bodyFontFamily: "Arial", bodyFontWeight: "normal", bodyFontStyle: "normal", bodyTextDecoration: "none", bodyTextColor: "#111111", bodyTextAlignment: "left", stripedRows: true, showBorders: true, titleAlignment: "left", orientation: "landscape", paperSize: "legal", captionText: "", noteText: "" }),
      benefit: reportCategory({ preset: "classic", primaryColor: "#7E22CE", headerBackground: "#F3E8FF", bodyFontSize: 9, bodyFontFamily: "Arial", bodyFontWeight: "normal", bodyFontStyle: "normal", bodyTextDecoration: "none", bodyTextColor: "#111111", bodyTextAlignment: "left", stripedRows: true, showBorders: true, titleAlignment: "center", orientation: "auto", paperSize: "a4", captionText: "", noteText: "" }),
      financial: reportCategory({ preset: "compact", primaryColor: "#0F172A", headerBackground: "#E2E8F0", bodyFontSize: 8, bodyFontFamily: "Arial", bodyFontWeight: "normal", bodyFontStyle: "normal", bodyTextDecoration: "none", bodyTextColor: "#111111", bodyTextAlignment: "left", stripedRows: true, showBorders: true, titleAlignment: "left", orientation: "landscape", paperSize: "letter", captionText: "", noteText: "" }),
    },
  },
}

export const DEFAULT_APPEARANCE_SETTINGS: AppearanceSettings = {
  sidebarLogoUrl: "/logo.png",
  sidebarFooterLeftLogoUrl: "/logo.png",
  sidebarFooterLeftLogoLabel: "GCGEA",
  sidebarFooterRightLogoUrl: "/city-seal-logo.png",
  sidebarFooterRightLogoLabel: "Gingoog City",
  showSidebarFooterLogos: false,
  primaryColor: "#1E3A8A",
  secondaryColor: "#2563EB",
  accentColor: "#D4AF37",
  sidebarColor: "#0F172A",
  backgroundColor: "#F8FAFC",
  progressColorStart: "#1E3A8A",
  progressColorMiddle: "#1E3A8A",
  progressColorEnd: "#1E3A8A",
  progressDarkColorStart: "#FFFFFF",
  progressDarkColorMiddle: "#FFFFFF",
  progressDarkColorEnd: "#FFFFFF",
  baseFontSize: 16,
  fontWeight: 400,
  fontFamily: "century-gothic",
  fontStyle: "normal",
  borderRadius: 10,
  compactMode: false,
  sidebarStyle: "expanded",
  logoSize: "medium",
  loginBackground: "default",
}
