import type { AppearanceSettings, NumberingFormatConfig, SystemSettings } from "@/types"
import { ORGANIZATION } from "@/constants/organization"

function numberingDefault(prefix: string, sequenceLength = 6): NumberingFormatConfig {
  return { prefix, includeYear: prefix !== "GCGEA-MEM", yearFormat: "YYYY", separator: "-", sequenceLength, startingNumber: 1 }
}

export const DEFAULT_SYSTEM_SETTINGS: SystemSettings = {
  general: {
    systemName: ORGANIZATION.systemName,
    systemShortName: ORGANIZATION.systemShortName,
    defaultLanguage: "English",
    timeZone: "Asia/Manila (UTC+8)",
    dateFormat: "MMMM d, yyyy",
    currency: "PHP (₱)",
    fiscalYearStart: "January",
    recordsPerPage: 10,
    maintenanceMode: false,
  },
  organization: {
    organizationName: ORGANIZATION.name,
    acronym: ORGANIZATION.acronym,
    address: ORGANIZATION.address,
    contactNumber: ORGANIZATION.contactNumber,
    email: ORGANIZATION.email,
    website: "www.gingoog.gov.ph",
    authorizedSignatoryName: "Maria Corazon D. Santos",
    authorizedSignatoryPosition: "GCGEA President",
    treasurerName: "Danilo T. Quiñones",
    presidentName: "Maria Corazon D. Santos",
  },
  numbering: {
    member: numberingDefault("GCGEA-MEM"),
    loan: numberingDefault("GCGEA-LN"),
    loanPayment: numberingDefault("GCGEA-PAY"),
    contribution: numberingDefault("GCGEA-CON"),
    benefit: numberingDefault("GCGEA-BEN"),
    benefitRelease: numberingDefault("GCGEA-BENREL"),
  },
  loan: {
    defaultInterestMethod: "Diminishing Balance",
    defaultInterestRate: 1.5,
    defaultProcessingFee: 200,
    defaultPenaltyRate: 2,
    gracePeriodDays: 5,
    maximumActiveLoans: 1,
    allowEligibilityOverride: true,
    requireApproval: true,
    requireReleaseConfirmation: true,
    allowPartialPayment: true,
    allowAdvancePayment: true,
    allowLoanRestructuring: true,
    defaultPaymentMethod: "Payroll Deduction",
    roundingRule: "Round to nearest centavo",
  },
  contribution: {
    defaultMonthlyContribution: 150,
    contributionDueDay: 5,
    allowPartialContribution: false,
    allowAdvanceContribution: true,
    payrollImportEnabled: true,
    duplicateHandling: "Skip duplicates",
    defaultPaymentMethod: "Payroll Deduction",
    requirePayrollReference: false,
    contributionReminderEnabled: true,
  },
  benefit: {
    requireApproval: true,
    requireReleaseConfirmation: true,
    allowEligibilityOverride: true,
    defaultApprovalLimit: 20000,
    defaultFrequencyLimit: "Once per year",
    requireSupportingDocuments: true,
    allowMultiplePendingApplications: false,
    benefitYearResetMonth: "January",
  },
  notification: {
    inAppNotifications: true,
    emailNotifications: false,
    smsNotifications: false,
    loanApprovalAlerts: true,
    loanDueDateAlerts: true,
    overdueLoanAlerts: true,
    benefitApprovalAlerts: true,
    contributionImportAlerts: true,
    incompleteProfileAlerts: true,
    userAccountAlerts: true,
  },
  security: {
    minimumPasswordLength: 8,
    requireUppercase: true,
    requireLowercase: true,
    requireNumber: true,
    requireSpecialCharacter: false,
    sessionTimeoutMinutes: 30,
    maximumLoginAttempts: 5,
    lockoutDurationMinutes: 15,
    requirePasswordChangeOnFirstLogin: false,
    enableTwoFactorAuth: false,
    auditSensitiveActions: true,
    confirmFinancialTransactions: true,
  },
  backup: {
    automaticBackup: true,
    backupFrequency: "Daily",
    retentionDays: 30,
    includeAttachments: false,
  },
}

export const DEFAULT_APPEARANCE_SETTINGS: AppearanceSettings = {
  primaryColor: "#1E3A8A",
  secondaryColor: "#2563EB",
  accentColor: "#D4AF37",
  sidebarColor: "#0F172A",
  backgroundColor: "#F8FAFC",
  borderRadius: 10,
  compactMode: false,
  sidebarStyle: "expanded",
  logoSize: "medium",
  loginBackground: "default",
}
